# -*- coding: utf-8 -*-
"""restaurant_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UkaTi5tYJDJMnxHrvMT-aWasLQQWDrez

**Data Exploration and Perprocessing**

Explore the dataset and identify the number of rows and columns
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv(r"Dataset .csv")
df.head()

df.shape

"""The dataset contains 9551 rows and 21 columns."""

df['Cuisines'].fillna("Unknown", inplace=True)

"""Missing values in the Cuisines column were replaced with "Unknown"."""

df.isnull().sum()

df.info()

"""Most columns already have appropriate data types, so no major data type conversion was required."""

df['Aggregate rating'].describe()

df['Aggregate rating'].value_counts()

plt.figure(figsize=(8,5))
sns.histplot(df['Aggregate rating'],color="blue", bins=10)
plt.title("Distribution of Aggregate Rating")
plt.show()

"""The distribution of Aggregate rating shows that most restaurants have ratings between 3.0 and 4.5, while a large number of restaurants have a rating of 0. This suggests a class imbalance in the dataset.

**Descriptive Analysis**
"""

df.describe()

"""The describe() function was used to calculate basic statistical measures for the numerical columns. It provides values such as mean, median (50%), standard deviation, minimum, maximum, and quartiles, which help summarize the distribution of the numerical data."""

print(df['Country Code'].value_counts())
print(df['City'].value_counts())
print(df['Cuisines'].value_counts())

"""The value_counts() function was used to analyze the distribution of categorical variables. It shows how many restaurants belong to each country, city, and cuisine category in the dataset."""

df['City'].value_counts().head(10)

"""The results show that New Delhi has the highest number of restaurants, followed by cities like Gurgaon and Noida"""

df['Cuisines'].value_counts().head(10)

"""The most common cuisines in the dataset include North Indian, North Indian & Chinese, Chinese, and Fast Food.

**Geospatial Analysis**
"""

import folium


map_center = [df['Latitude'].mean(), df['Longitude'].mean()]
restaurant_map = folium.Map(location=map_center, zoom_start=5)


for i, row in df.iterrows():
    folium.CircleMarker(
        location=[row['Latitude'], row['Longitude']],
        radius=3,
        popup=row['Restaurant Name'],
        color='blue',
        fill=True
    ).add_to(restaurant_map)

restaurant_map

"""An interactive map was created using folium. The map was centered using the average latitude and longitude. Each restaurant was plotted using circular markers, and clicking on a marker displays the restaurant name. This visualization helps understand the geographical distribution of restaurants"""

city_counts = df['City'].value_counts()

print(city_counts.head(10))

import matplotlib.pyplot as plt

city_counts.head(10).plot(kind='bar',color="blue")
plt.title("Top 10 Cities with Most Restaurants")
plt.xlabel("City")
plt.ylabel("Number of Restaurants")
plt.show()

country_counts = df['Country Code'].value_counts()
print(country_counts)

"""The distribution of restaurants across cities and countries was analyzed using value counts and bar plots. It was observed that certain cities have a significantly higher number of restaurants, indicating higher urban density and demand. Similarly, some countries dominate the dataset with a larger number of restaurants, while others have relatively fewer entries. This shows that the dataset is not evenly distributed geographically."""

correlation = df[['Latitude', 'Longitude', 'Aggregate rating']].corr()
print(correlation)

import seaborn as sns

sns.heatmap(correlation, annot=True, cmap='coolwarm')
plt.show()

"""The heatmap indicates weak correlations, meaning restaurant location does not significantly affect ratings.

**Predictive Modeling**
"""

df = pd.read_csv('Dataset .csv')
df.info()

df.isnull().sum()

df['Cuisines'].fillna("Unknown", inplace=True)

df = df.drop(['Restaurant ID', 'Restaurant Name', 'Address',
              'Locality', 'Locality Verbose', 'Currency',
              'Rating color', 'Rating text'], axis=1)

yes_no_cols = ['Has Table booking', 'Has Online delivery', 'Is delivering now', 'Switch to order menu']
for col in yes_no_cols:
    df[col] = df[col].map({'Yes': 1, 'No': 0})

df = pd.get_dummies(df, columns=['City', 'Cuisines'], drop_first=True)

print(df.info())

X = df.drop('Aggregate rating', axis=1)
y = df['Aggregate rating']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

models = {
    "Linear Regression": LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(random_state=42),
    "Random Forest": RandomForestRegressor(random_state=42, n_estimators=100)
}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    r2 = r2_score(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)

    print("=================================")
    print(name)
    print("R2 Score:", r2)
    print("RMSE:", rmse)

"""The performance of the regression models was evaluated using R² Score and Root Mean Squared Error (RMSE). R² Score measures how well the model explains the variability in the target variable, while RMSE measures the average error between predicted and actual values. A higher R² score and lower RMSE indicate better model performance. The Random Forest model achieved the highest R² score and lowest RMSE, making it the best-performing model.

A regression model was built to predict the aggregate rating of restaurants using features such as location, cost, online delivery, table booking, price range, and votes. The dataset was split into training and testing sets in an 80:20 ratio. Three regression models were trained: Linear Regression, Decision Tree Regressor, and Random Forest Regressor. The models were evaluated using R² Score and Root Mean Squared Error (RMSE). Linear Regression performed poorly with a low R² score of 0.119 and high RMSE of 1.41. Decision Tree performed significantly better with an R² score of 0.932 and RMSE of 0.39. Random Forest achieved the best performance with the highest R² score of 0.961 and lowest RMSE of 0.30. Therefore, Random Forest was identified as the best model for predicting restaurant aggregate ratings.

**Customer Preference Analysis**
"""

import pandas as pd

df = pd.read_csv("Dataset .csv")
df['Cuisines'].fillna('Unknown', inplace=True)

cuisine_rating = df.groupby('Cuisines')['Aggregate rating'].mean().sort_values(ascending=False)

print("Average Rating by Cuisine:")
print(cuisine_rating.head(10))

cuisine_votes = df.groupby('Cuisines')['Votes'].sum().sort_values(ascending=False)
print(cuisine_votes.head(10))

cuisine_analysis = df.groupby('Cuisines').agg({
    'Aggregate rating': 'mean',
    'Votes': 'sum'
}).sort_values(by='Aggregate rating', ascending=False)

print(cuisine_analysis.head(10))

"""The relationship between cuisine type, ratings, and votes was analyzed to understand customer preferences. It was observed that several cuisines such as Italian, American, BBQ, Seafood, and Mughlai received very high average ratings (around 4.9). Among these, cuisines such as Italian, American BBQ, Hawaiian Seafood, and Mughlai had a higher number of votes, indicating that these cuisines are not only highly rated but also popular among customers. This shows that these cuisines are the most preferred by customers based on both rating and popularity.

**Data Visualization**
"""

plt.figure(figsize=(8,5))
plt.hist(df['Aggregate rating'], bins=10,color="blue")
plt.title("Distribution of Restaurant Ratings")
plt.xlabel("Rating")
plt.ylabel("Number of Restaurants")
plt.show()

rating_counts = df['Aggregate rating'].value_counts().sort_index()

plt.figure(figsize=(8,5))
plt.bar(rating_counts.index, rating_counts.values,color="blue")
plt.title("Count of Each Rating")
plt.xlabel("Aggregate Rating")
plt.ylabel("Number of Restaurants")
plt.show()

plt.figure(figsize=(10,5))
sns.countplot(x='Aggregate rating', data=df,color="blue")
plt.title("Distribution of Ratings (Count Plot)")
plt.show()

"""The distribution of restaurant ratings was visualized using histogram and bar plots. The histogram showed that most restaurants have ratings between 3.0 and 4.5, indicating that the majority of restaurants are moderately to highly rated. The bar plot showed the count of restaurants for each rating value, and it was observed that very few restaurants have extremely low ratings, while most restaurants have average to good ratings."""

top_cuisines = df['Cuisines'].value_counts().head(10).index
cuisine_data = df[df['Cuisines'].isin(top_cuisines)]

avg_rating_cuisine = cuisine_data.groupby('Cuisines')['Aggregate rating'].mean()

avg_rating_cuisine.plot(kind='bar', figsize=(10,5),color="blue")
plt.title("Average Rating by Top 10 Cuisines")
plt.xlabel("Cuisine")
plt.ylabel("Average Rating")
plt.xticks(rotation=45)
plt.show()

top_cities = df['City'].value_counts().head(10).index
city_data = df[df['City'].isin(top_cities)]

avg_rating_city = city_data.groupby('City')['Aggregate rating'].mean()

avg_rating_city.plot(kind='bar', figsize=(10,5),color="blue")
plt.title("Average Rating by Top 10 Cities")
plt.xlabel("City")
plt.ylabel("Average Rating")
plt.xticks(rotation=45)
plt.show()

"""Bar charts were used to compare the average ratings of different cuisines and cities. The visualization showed that average ratings vary across different cuisines, indicating that customer satisfaction depends on the type of cuisine offered. Similarly, the average ratings also vary across cities, which may be due to differences in food quality, service, and customer preferences in different locations."""

plt.figure(figsize=(8,5),)
plt.scatter(df['Votes'], df['Aggregate rating'],color="blue")
plt.title("Votes vs Aggregate Rating")
plt.xlabel("Votes")
plt.ylabel("Aggregate Rating")
plt.show()

plt.figure(figsize=(8,5))
plt.scatter(df['Average Cost for two'], df['Aggregate rating'],color="blue")
plt.title("Cost vs Aggregate Rating")
plt.xlabel("Average Cost for Two")
plt.ylabel("Aggregate Rating")
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(x='Price range', y='Aggregate rating', data=df,color="blue")
plt.title("Price Range vs Rating")
plt.show()

plt.figure(figsize=(8,6))
sns.heatmap(df[['Aggregate rating', 'Votes', 'Average Cost for two', 'Price range']].corr(),
            annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

"""Various visualizations were used to understand the relationship between different features and restaurant ratings. Scatter plots showed that votes and cost have a positive relationship with ratings, indicating that popular and higher-cost restaurants tend to have higher ratings. The box plot showed that restaurants with higher price ranges generally have higher ratings. The heatmap showed a positive correlation between votes, price range, and aggregate rating. These visualizations help in understanding the factors that influence restaurant ratings."""